version: '3'
services:
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reactive-postgres
      POSTGRES_DB: reactive-postgres
    ports:
      - "5432:5432"